### ISSUE TITLE
simulated camera stalling

### ISSUE THREAD

**Issue by nclack** [acquire-project/acquire-common#7]
We've seen examples where there's excessive lock contention in the rendering thread for the simulated camera. This can cause stalls in some cases. It seems especially prevalent on os x.

It does not happen super reproducibly.

See this [test failure](https://github.com/acquire-project/acquire-video-runtime/actions/runs/6305538040/job/17119128683?pr=100#step:7:26)

**Comment by aliddell** [comment]
Image render thread (`simulated_camera_streamer_thread`) will generate a frame, release the lock, and then reacquire the lock before the video source thread (in `simcam_get_frame`) can grab it.

**Comment by aliddell** [comment]
To test, the best simulated image type is radial sine.

**Comment by nclack** [comment]
closed by #47
